[package]
name = "pmecs"
version = "0.1.0"
edition = "2021"
authors = ["bugthesystem"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.12.1"
rayon = "1.7.0"
